### ISSUE TITLE
add GStreamer-VAAPI plugin for hardware accelerated video decode

### ISSUE THREAD

**Issue by rajveermalviya** [flathub/org.gnome.Epiphany#15]
currently it's not added

```shell
rajveer@xps-13 ~> flatpak run --command=bash org.gnome.Epiphany 
[📦 org.gnome.Epiphany ~]$ gst-inspect-1.0 vaapi
No such element or plugin 'vaapi'
```

Refs -
https://wiki.archlinux.org/index.php/GNOME/Web
https://gstreamer.freedesktop.org/documentation/vaapi/index.html?gi-language=c
https://wiki.archlinux.org/index.php/GStreamer

**Comment by rajveermalviya** [comment]
Seems like it was discussed to create a flatpak extension

https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/118 (adding to org.gnome.Platform - dropped because of extension)
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/1750 (creating an extension - no update yet)

is it possible to bundle it till the extension is created?

**Comment by mcatanzaro** [comment]
I don't think this is a good idea. gstreamer-vaapi has a history of breaking video playback and is still considered unstable. That's why it's not installed by default in distros, and why it should be an extension rather than something installed automatically.

If GStreamer developers (CC @alatiera) think it has improved to the point that it's OK to install by default in distros, then that would be a different situation.

**Comment by alatiera** [comment]
@ceyusa would be the best person to ask about vaapi.

On flatpak related things, there's also some weird missmatch with the mesa driver intel systems are using since there are 2 of them iHD and i915. But I am not aware how that operates either. maybe @nanonyme knows?

**Comment by nanonyme** [comment]
@alatiera do you mean the i965 vs iris mess Intel dug us all into by switching hardware already supported by i965 into iris instead? We changed default for these hardware supported by multiple hardware to i965 in 19.08 in order to try to balance between crashes and support but we may still be switching the default on 20.08 since there's reports of crashes if host has iris and flatpak has i965 https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/3340

**Comment by nanonyme** [comment]
I have no idea about VAAPI situation.

**Comment by nanonyme** [comment]
Ah, yes, right, gstreamer-vaapi was indeed removed due to complaints of it resulting in crashes. It might be reasonable to still add the extension for 20.08.

**Comment by nanonyme** [comment]
I think the extension work was stuck because we couldn't agree whether it should be called gstreamer-vaapi or gst-vaapi :) https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/1750

**Comment by nanonyme** [comment]
Created upstream issue at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1152

**Comment by nanonyme** [comment]
Plan is gstreamer-vaapi will return as an extension in freedesktop-sdk 21..08.

**Comment by mcatanzaro** [comment]
After discussion with the gstreamer-vaapi maintainer, he advised us that gstreamer-vaapi 1.16 is not good enough to include yet and that we should wait for 1.18 instead. That means waiting until GNOME 41 for next year's freedesktop-sdk.
