### ISSUE TITLE
Can't play videos on Wayland

### ISSUE THREAD

**Issue by VarLad** [flathub/org.gnome.Epiphany#37]
Sites like Youtube when used to play videos on Wayland. 
XWayland works properly

**Comment by mcatanzaro** [comment]
Feel free to report this on WebKit Bugzilla, Media component. Prefix the title of your bug with `[GStreamer]` and CC `bugs-noreply@webkitgtk.org`. Please also attach a debug log following the instructions at https://trac.webkit.org/wiki/WebKitGTK/Debugging#Debuggingmultimediastuff. Thanks!

**Comment by VarLad** [comment]
@mcatanzaro This doesn't happen with the version of Epiphany installed from the package manager. It uses WebKitGTK 2.36.2. 
I see that the Flatpak version uses WebKitGTK 2.36.1
Before filing an issue, I'd like to make sure that its 
1. Not a Flatpak issue
2. Not a regression fixed in WebKitGTK 2.36.2

**Comment by VarLad** [comment]
For reference, I'm using Fedora SilverBlue 36 (Wayland) (I installed Epiphany in a toolbox to try it though)

**Comment by mcatanzaro** [comment]
It's unlikely that any changes in 2.36.2 are related.

Only only advice I have is to make sure you don't have the gstreamer-vaapi flatpak extension installed.

Even if the bug only occurs in flatpak, there's zero chance of it being resolved anywhere other than WebKit Bugzilla, so I recommend reporting it there anyway. Most likely the behavior difference is related to older GStreamer rather than anything else.
